# Generated by Django 3.2.8 on 2021-10-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_discord_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_guild',
            name='guild_uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discord_user',
            name='discord_uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
