# Generated by Django 3.2.8 on 2021-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20211008_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_user',
            name='guilds',
            field=models.ManyToManyField(to='discord.Discord_Guild'),
        ),
    ]
